###############################################################################
# config.sh — single source of truth for pipeline paths
#
# Every BSUB script in this directory does:
#     source /projectnb/dcrawford/MT_Genomics2/jobs/config.sh
#
# To relocate data, change the paths below — DO NOT edit individual scripts.
#
# Layout note (2026-05-07):
#   - Sample list, reference, BAMs, VCFs are CONSOLIDATED under
#     /projectnb/dcrawford/MT_Genomics2/.
#   - Trimmed reads (2.1 TB) and trimmed FastQC outputs stay in place
#     under /projectnb/dcrawford/SSM_WGS/ — too large or pointless to move
#     since they're regeneratable from cold-storage raw.
#   - Raw reads are in cold storage; stages 01 + 02 cannot run as-is.
#   - BAMs (stage 04) and joint-call VCFs (stage 05) will be REGENERATED
#     into the consolidated layout — the previous SSM_Mito/MT_bam_sam/
#     and SSM_Mito/new_hap_AD/ directories are missing as of 2026-05-07.
###############################################################################

# ── Project root (mirrored from Mac) ─────────────────────────────────────────
PROJECT_ROOT=/projectnb/dcrawford/MT_Genomics2
LOGS_DIR="${PROJECT_ROOT}/logs"

###############################################################################
# DATA + REFERENCE LOCATIONS
###############################################################################

# ── Sample list (consolidated) ───────────────────────────────────────────────
SAMPLE_LIST="${PROJECT_ROOT}/SSM_WGS_list.txt"

# ── Reads ────────────────────────────────────────────────────────────────────
# Raw reads in cold storage — stages 01 + 02 will fail at the input-existence
# check if invoked. Path retained as a record of the original location.
RAW_DIR=/projectnb/dcrawford/SSM_WGS/fhet_raw_seq          # NOT PRESENT (cold storage)

# Trimmed reads stay in place (large, regeneratable).
TRIM_DIR=/projectnb/dcrawford/SSM_WGS/trimmed_seq

# ── FastQC outputs ───────────────────────────────────────────────────────────
# Raw FastQC dropped 2026-05-07 (trimmed FastQC is sufficient; raw is in
# cold storage anyway).
RAW_QC_DIR=/projectnb/dcrawford/SSM_WGS/fastqc_out         # DROPPED (kept as sentinel)

# Trimmed FastQC stays in place.
TRIM_QC_DIR=/projectnb/dcrawford/SSM_WGS/fastqc_TrimA

# ── Reference (consolidated) ─────────────────────────────────────────────────
# Restored from Mac backup ~/Projects/SSM_Mito_All/SSM_MT_ref/ on 2026-05-07.
# Contents: Fhet_MT.fasta + .fai + .amb + .ann + .bwt + .pac + .sa + Fhet_MT.gff
REF="${PROJECT_ROOT}/refs/Fhet_MT.fasta"
GFF="${PROJECT_ROOT}/refs/Fhet_MT.gff"

# ── BAMs (consolidated; regenerated by stage 04 rerun) ───────────────────────
BAMS_DIR="${PROJECT_ROOT}/bams"

# ── VCFs (consolidated; regenerated by stage 05 rerun) ───────────────────────
VCF_DIR="${PROJECT_ROOT}/vcf"

# BAM list — produced after stage 04 finishes, consumed by stage 05:
#     ls "$BAMS_DIR"/*_MT.bam | xargs -n1 basename > "$BAM_LIST"
BAM_LIST="${PROJECT_ROOT}/bam_list.txt"

# ── External tools (Trimmomatic jar lives outside the project) ───────────────
TRIMJAR=/home/dcrawford/software/local/Trimmomatic-0.39/trimmomatic-0.39.jar
ADAPTERS=/home/dcrawford/software/local/Trimmomatic-0.39/adapters/CombinedAdapters.fa
# If you install trimmomatic via conda instead, comment the two lines above and
# call `trimmomatic PE ...` directly in 02_trim_pe.sh.

# ── Conda module + environment ────────────────────────────────────────────────
# Confirmed 2026-05-08:
#   base  : /sw/summit/software/linux-power9le/anaconda3-2023.09-0-...  (read only)
#   env   : /projectnb/triton/home/dcrawford/.conda/envs/mito_genomics
# The env is user-level (.conda/envs/) and is found by conda once the right
# base module is loaded.
CONDA_MODULE=anaconda3/2023.09-0-none-none-oawyzwj
CONDA_ENV=mito_genomics

# Load conda and register shell hooks so `conda activate` works on compute nodes.
# `module load` puts conda in PATH but does not register the activate shell
# function; `eval "$(conda shell.bash hook)"` does that for modern conda (>=4.4).
# Sourcing config.sh propagates this to every BSUB script automatically.
module load "$CONDA_MODULE"
eval "$(conda shell.bash hook)"

# ── Locally-built bcftools / samtools / htslib 1.23.1 (DEFAULT) ──────────────
# Why: bcftools 1.6 in the mito_genomics conda env produces a silent variant-
# count collapse on high-depth mtDNA pileups — 3-sample test returned 6 SNPs
# (1.6) vs 289 (1.23.1) from the same BAMs and recipe. See CHANGELOG
# 2026-05-15. Built from source on Triton 2 (linux-ppc64le, where bioconda
# pins to 1.6); binaries in ~/software/local/bin/, libs in ~/software/local/lib/.
#
# ORDERING CAVEAT: `conda activate "$CONDA_ENV"` prepends the env's bin to
# PATH, which re-shadows these exports. For BSUB scripts that source
# config.sh AND then conda activate, re-export both lines AFTER
# `conda activate` (or skip conda activation entirely — preferred for any
# script whose only env need is bcftools/samtools/htslib).
export PATH="$HOME/software/local/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/software/local/lib:${LD_LIBRARY_PATH:-}"

# ── Make sure logs directory exists (idempotent) ─────────────────────────────
mkdir -p "$LOGS_DIR"
